apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-front
  labels:
    app: udagram-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-front
  template:
    metadata:
      labels:
        app: udagram-front
    spec:
      containers:
      - name: udagram-front
        image: abdallahelshamy/udagram-front
        ports:
        - containerPort: 8080
